
version: 2

sources:
  - name: staging
    database: dez-final-project
    schema: energy_data
    tables:
      - name: energy_consumption_data
      - name: hydropower_generation_data
      - name: dams_data

models:
    - name: stg_energy_consumption_data
      description: "Records for world energy consumption"
      columns:
          - name: country
            description: "Country - Geographic location."
            tests:
                - unique
                - not_null
          - name: year
            description: "Year - Year of observation."
          - name: iso_code
            description: "ISO code - ISO 3166-1 alpha-3 three-letter country codes."
          - name: population
            description: "Population - Population by country, available from 10,000 BCE to 2100, based on data and estimates from different sources."
          - name: electricity_demand
            description: "Electricity demand - Measured in terawatt-hours."
          - name: electricity_generation
            description: "Total electricity generation - Measured in terawatt-hours."
          - name: electricity_share_energy
            description: "Total electricity generation as share of primary energy - Measured as a percentage of total, direct primary energy consumption."
          - name: energy_per_capita
            description: "Primary energy consumption per capita - Measured in kilowatt-hours per person."
          - name: hydro_consumption
            description: "Primary energy consumption from hydropower - Measured in terawatt-hours, using the substitution method."
          - name: hydro_elec_per_capita
            description: "Electricity generation from hydropower per person - Measured in kilowatt-hours per person."
          - name: hydro_electricity
            description: "Electricity generation from hydropower - Measured in terawatt-hours."
          - name: hydro_energy_per_capita
            description: "Hydropower consumption per capita - Measured in kilowatt-hours per person."
          - name: hydro_share_elec
            description: "Share of electricity generated by hydropower - Measured as a percentage of total electricity."
          - name: hydro_share_energy
            description: "Share of primary energy consumption that comes from hydropower - Measured as a percentage of the total primary energy, using the substitution method."
          - name: per_capita_electricity
            description: "Total electricity generation per person - Measured in kilowatt-hours per person."
          - name: primary_energy_consumption
            description: "Primary energy consumption - Measured in terawatt-hours."

    - name: stg_hydropower_generation_data
      description: "Records for world energy generated by hydropower."
      columns:
        - name: country
          tests:
              - unique
              - not_null
          description: "Country"
        - name: iso_code
          description: "ISO code - ISO 3166-1 alpha-3 three-letter country codes."
        - name: year
          description: "Year - Year of observation."
        - name: hydro_generation
          description: "Electricity generation from hydropower - Measured in terawatt-hours."

    - name: stg_world_dams_data
      description: "World dams for hydropower generation by country."
      columns:
        - name: country
          tests:
              - unique
              - not_null
          description: "Country"
        - name: iso_code
          description: "ISO code - ISO 3166-1 alpha-3 three-letter country codes."
        - name: purpose
          description: "Purpose of dam."
        - name: total_hydropowers_dams
          description: "Total number of dams for hydropower generation."
